version: '3.8'
services:
  postgres:
    image: postgres:15.5
    ports:
      - '5032:5432'
    environment:
      TZ: 'Asia/Bangkok'
      POSTGRES_DB: ectopic_social_tool_local
      POSTGRES_USER: ectopic_social_tool_local
      POSTGRES_PASSWORD: localpass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - 'pg_data:/var/lib/postgresql/data/pgdata'
  redis:
    image: 'redis:7.2'
    ports:
      - '6079:6379'
    volumes:
      - 'redis_data:/data'

volumes:
  redis_data:
  pg_data:
